version: "3.7"
services:
  zalenium:
    image: dosel/zalenium
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "4444:4444"
    networks:
      - zalenium
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/videos:/home/seluser/videos
    environment:
      - PULL_SELENIUM_IMAGE=true
    command: ["start", "--swarmOverlayNetwork", "<stack-name>_zalenium", "--videoRecordingEnabled", "false"]
networks:
  zalenium:
    driver: overlay
    attachable: true