{{- if and (.Values.persistence.enabled) (not .Values.persistence.useExisting) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  "{{- if not (empty .Values.persistence.data.name) }}{{ .Values.persistence.data.name }}{{- else }}{{ template "hub.fullname" . }}{{- end }}-data"
  labels:
    app: "{{- if not (empty .Values.persistence.data.name) }}{{ .Values.persistence.data.name }}{{- else }}{{ template "fullname" . }}{{- end }}"
    role: grid
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- if .Values.persistence.data.storageClass }}
{{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.data.storageClass }}"
{{- end }}
{{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{- if not (empty .Values.persistence.video.name) }}{{ .Values.persistence.video.name }}{{- else }}{{ template "hub.fullname" . }}{{- end }}-videos"
  labels:
    app: "{{- if not (empty .Values.persistence.video.name) }}{{ .Values.persistence.video.name }}{{- else }}{{ template "fullname" . }}{{- end }}"
    role: grid
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.video.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.video.size | quote }}
{{- if .Values.persistence.video.storageClass }}
{{- if (eq "-" .Values.persistence.video.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.video.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
