{{- if and (.Values.persistence.enabled) (not .Values.persistence.data.useExisting) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ template "zalenium.fullname" . }}-data"
  labels:
    app: {{ template "zalenium.name" . }}
    role: grid
    chart: {{ template "zalenium.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- if .Values.persistence.data.storageClass }}
{{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.data.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
---
{{- if and (.Values.persistence.enabled) (not .Values.persistence.video.useExisting) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ template "zalenium.fullname" . }}-videos"
  labels:
    app: {{ template "zalenium.name" . }}
    role: grid
    chart: {{ template "zalenium.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.video.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.video.size | quote }}
{{- if .Values.persistence.video.storageClass }}
{{- if (eq "-" .Values.persistence.video.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.video.storageClass }}"
{{- end }}
{{- end }}
{{- end }}