language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - docker pull elgalu/selenium

script:
#  - mvn clean verify -Pintegration-test -DthreadCountProperty=2 -Dskip.surefire.tests=true
  - mvn clean package -Pcoverage-report
  - ./runSonarQubeAnalysis.sh

after_script:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

# branches safe list to build
branches:
  only:
  - master