apiVersion: v1
entries:
  zalenium:
  - appVersion: 3.4.0
    created: 2019-03-06T11:00:09.547856+11:00
    description: Chart for selenium grid
    digest: 75bd489baf1f1050d78452a99df2bf2a158690b1102f86ff3e900251f771bcbb
    engine: gotpl
    home: https://github.com/zalando/zalenium
    keywords:
    - qa
    maintainers:
    - email: diemol@gmail.com
      name: diemol
    name: zalenium
    sources:
    - https://github.com/zalando/zalenium
    urls:
    - zalenium-0.0.1.tgz
    version: 0.0.1
generated: 2019-03-06T11:00:09.547029+11:00
